### ISSUE TITLE
Widget packages could not be read error

### ISSUE THREAD

**Issue by aleworth** [kendallchristy/mendix-GTM-PageView#1]
Upon downloading the widget from marketplace I immediately get the following pop up:
![image](https://user-images.githubusercontent.com/9449820/211082830-fb8566fc-4342-4300-9b9e-1fc39161d39b.png)

With the error message:
Widget xml file 'GoogleTagManager.xml' not found.

I am using version 9.18.2 and 9.12.6 and experiencing the same issue in both. The widget doesn't appear in the toolbox either. I can see it in my app's local files (app/widgets), however there is an issue with the widget as it is not currently working properly.

Please let me know if there is anything else I can provide you with to help resolve the issue. Thank you!

**Comment by kendallchristy** [comment]
Hi @aleworth ,

I've just created a new release and published it to the mendix marketplace. Take a look and let me know if you continue to have issues.
